### ISSUE TITLE
what is the license for this software?

### ISSUE THREAD

**Issue by henrikcozza** [favrora/Avatar-Maker#23]
what is the license for this software?

Hugs

**Comment by favrora** [comment]
Hey! Thanks for the created task. I'll add the license a little later.

**Comment by mathiasbosman** [comment]
Is this related to https://getavataaars.com/?

**Comment by favrora** [comment]
@mathiasbosman  No.) I have not seen this site before, but apparently they also used avatars similar to ours.

**Comment by favrora** [comment]
I took these SVG avatars from another project, I drew some of them myself.

**Comment by favrora** [comment]
Completed
