### ISSUE TITLE
Create Demo Site

### ISSUE THREAD

**Issue by andrewkliskey** [favrora/Avatar-Maker#6]
Hi,

You've got a pretty cool project here!

It would be better if you didn't have to run it locally and you had a demo site.

This could be achieved very quickly and for free with [Netlify](https://netlify.com), I think [Vercel](https://vercel.com/) have similar offerings.

I got this set up in under 5 mins: https://avatar-maker-demo.netlify.app

Happy to help out if you bump into any issues :)

**Comment by favrora** [comment]
Hey! Thank you very much for your help, yes I agree. I will add a demo
version to my project description and mark you as completing this task.

Now the priority is to implement the functionality for loading an avatar in
the form of an image.

Thank you very much for your help!

ср, 3 февр. 2021 г. в 22:11, Andrew Kliskey <notifications@github.com>:
